=== NLeSC/LIEStudio/components/lie_workflow/lie_workflow/workflow_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://liestudio/schemas/workflow_schema.json",
    "title": "Workflow",
    "description": "A default LIEStudio workflow",
    "type": "object",
    "properties": {
        "graph": {
            "type": "object",
            "properties": {
                "title": {
                    "description": "Administrative title of the task",
                    "type": "string",
                    "default": "MDstudio workflow"
                },
                "description": {
                    "description": "Description of the task",
                    "type": "string",
                    "default": ""
                },
                "version": {
                    "description": "workflow version",
                    "type": "number",
                    "default": 1.0
                },
                "is_running": {
                    "description": "Is the workflow currently running or not",
                    "type": "boolean",
                    "default": false
                },
                "create_time": {
                    "description": "Workflow creation time stamp",
                    "type": "integer"
                },
                "update_time": {
                    "description": "Last workflow update time stamp",
                    "type": "integer"
                },
                "start_time": {
                    "description": "Workflow run start time stamp",
                    "type": "integer"
                },
                "node_data_tag": {
                    "description": "",
                    "type": "string",
                    "default": "task_name"
                },
                "is_directed": {
                    "description": "",
                    "type": "boolean",
                    "default": true,
                    "enum": [ true ]
                },
                "edge_data_tag": {
                    "description": "",
                    "type": "string",
                    "default": "label"
                },
                "is_masked": {
                    "description": "",
                    "type": "boolean",
                    "default": false
                },
                "root": {
                    "description": "",
                    "type": "integer",
                    "default": 1
                }, 
                "auto_nid": {
                    "description": "",
                    "type": "boolean",
                    "default": true
                }
            },
            "required": ["title", "description", "is_running", "is_directed", "root", "node_data_tag"]
        },
        "edges": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^.*$": {
                    "allOf": [
                        {
                            "type": "array",
                            "minItems": 2,
                            "uniqueItems": true
                        }
                    ]
                }
            }
        },
        "edge_attr":{
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^.*$": {
                    "type": "object",
                    "properties": {
                        "data_mapping": {
                            "description": "Keyword mapping between output/input data attribute names",
                            "type": "object"
                        }
                    }
                }
            }
        },
        "nodes": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^.*$": {
                    "type": "object",
                    "properties": {
                        "active": {
                            "description": "Is the current task active or not",
                            "type": "boolean",
                            "default": false
                        },
                        "breakpoint": {
                            "description": "Add a breakpoint for the task. The workflow will only continue if explicitly instructed",
                            "type": "boolean",
                            "default": false
                        },
                        "custom_func": {
                            "type": "string",
                            "description": "Custom Python function to run in a (local) task runner",
                            "pattern": "^\\w+(\\.\\w+)*$"
                        },
                        "input_data": {
                            "description": "All required input and optional configuration to the service as key/value pairs",
                            "type": "object",
                            "default": {}
                        },
                        "output_data": {
                            "description": "All output returned by the task as key/value pairs",
                            "type": "object"
                        },
                        "retry_count": {
                            "description": "Number of times the task should be resubmitted when it failed",
                            "type": "integer",
                            "default": 0
                        },
                        "session": {
                            "description": "Session specific data",
                            "type": "object"
                        },
                        "status": {
                            "description": "The status of the current task",
                            "type": "string",
                            "default": "ready",
                            "enum": ["ready","submitted","running","failed","aborted","completed","disabled"]
                        },
                        "store_output": {
                            "description": "Store the output of the task to disk",
                            "type": "boolean",
                            "default": false
                        },
                        "task_id": {
                            "type": "string",
                            "description": "Unique ID used to identify the task in the system"
                        },
                        "uri": {
                            "type": "string",
                            "description": "LIEStudio microservice method uri",
                            "pattern": "^\\w+(\\.\\w+)*$"
                        }
                    },
                    "required": ["active", "breakpoint", "retry_count", "status"]
                }
            }
        },
        "lie_graph_version": {
            "type": "string",
            "default": "1.0"
        }
    },      
    "required": ["lie_graph_version", "graph"]
}

=== NLeSC/LIEStudio/components/lie_workflow/tests/files/test-workflow-spec.json
{
  "edge_attr": {}, 
  "graph": {
    "title": "Linear workflow (finished)",
    "description": "A simple 6 node linear workflow",
    "node_data_tag": "task_name",
    "create_time": 1493819360,
    "start_time": 1493819365,
    "update_time": 1493819372,
    "is_directed": true,
    "is_running": true,
    "edge_data_tag": "label", 
    "is_masked": false, 
    "root": 1, 
    "auto_nid": true
  }, 
  "edges": {
    "0": [
      1, 
      2
    ], 
    "1": [
      1, 
      3
    ], 
    "2": [
      1, 
      4
    ], 
    "3": [
      1, 
      5
    ], 
    "4": [
      2, 
      6
    ],
    "5": [
      3, 
      6
    ],
    "6": [
      4, 
      6
    ],
    "7": [
      5, 
      6
    ]
  },
  "nodes": {
    "1": {
      "status": "completed",
      "task_name": "start", 
      "nid": 1, 
      "retry_count": 0, 
      "breakpoint": false, 
      "active": false, 
      "output_data": {
        "file": "input"
      },
      "session": {
          "status": "completed", 
          "utime": 1493819365,
          "itime": 1493819365, 
          "system_user": "mvdijk", 
          "task_id": "1493819367-6252"
      },
      "_id": 1, 
      "task_type": "Start"
    }, 
    "2": {
      "status": "completed",
      "input_data": {
        "sleep": 1
      },  
      "output_data": {
        "file": "task1"
      },
      "session": {
          "status": "completed", 
          "system_user": "mvdijk", 
          "task_id": "1493819367-6146",
          "itime": 1493819367,
          "utime": 1493819368 
      },
      "task_name": "task1", 
      "nid": 2, 
      "retry_count": 0, 
      "breakpoint": false, 
      "active": false, 
      "_id": 2, 
      "task_type": "Task"
    }, 
    "3": {
      "status": "completed",
      "input_data": {
        "sleep": 1
      },
      "output_data": {
        "file": "task2"
      },
      "session": {
          "status": "completed",
          "itime": 1493819368,
          "utime": 1493819369,
          "system_user": "mvdijk", 
          "task_id": "1493819368-7176"
      },
      "task_name": "task2", 
      "nid": 3, 
      "retry_count": 0, 
      "breakpoint": false, 
      "active": false, 
      "_id": 3, 
      "task_type": "Task"
    }, 
    "4": {
      "status": "completed",
      "input_data": {
        "sleep": 1
      },
      "output_data": {
        "file": "task3"
      },
      "session": {
          "status": "completed",
          "system_user": "mvdijk", 
          "task_id": "1493819369-6710",
          "itime": 1493819369,
          "utime": 1493819370
      },
      "task_name": "task3", 
      "nid": 4, 
      "retry_count": 0,  
      "breakpoint": false, 
      "active": false, 
      "_id": 4, 
      "task_type": "Task"
    }, 
    "5": {
      "status": "completed",
      "input_data": {
        "sleep": 1
      },
      "output_data": {
        "file": "task4"
      },
      "session": {
          "status": "completed",
          "system_user": "mvdijk", 
          "task_id": "1493819370-5050",
          "itime": 1493819370,
          "utime": 1493819371
      },
      "task_name": "task4", 
      "nid": 5, 
      "retry_count": 0,  
      "breakpoint": false, 
      "active": false, 
      "_id": 5, 
      "task_type": "Task"
    }, 
    "6": {
      "status": "running",
      "input_data": {
        "sleep": 1
      },
      "task_name": "task5", 
      "nid": 6, 
      "retry_count": 0,  
      "breakpoint": false, 
      "active": false, 
      "_id": 6, 
      "task_type": "Task"
    }
  }, 
  "lie_graph_version": "0.1"
}
